### ISSUE TITLE
 runner.sh script - module: command not found error

### ISSUE THREAD

**Issue by pudding-art** [bsc-mem/Mess-benchmark#1]
When running the ./Mess-benchmark-main/CPU/Actual-hardware/x86/Intel-SapphireRapids-Xeon-Platinum-8480/runner.sh script, I encountered the following error messages:

```
./runner.sh: line 3: module: command not found
./runner.sh: line 4: module: command not found
./runner.sh: line 5: module: command not found
./runner.sh: line 6: module: command not found
./runner.sh: line 7: module: command not found
./runner.sh: line 8: module: command not found
./runner.sh: line 10: module: command not found
```
The runner.sh script includes environment-related commands such as `module purge` and `module load` to manage software modules and environment variables.
```
module purge
module load bsc/1.0
module load intel/2023.2.0
module load impi/2021.9.0
module load oneapi/2023.2.0
module load mkl/2023.2.0

module load hdf5 python/3.12.1
```

```
hwt@server2:~/workspace/Mess-benchmark-main/CPU/Actual-hardware/x86/Intel-SapphireRapids-Xeon-Platinum-8480$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 57 bits virtual
  Byte Order:            Little Endian
CPU(s):                  192
  On-line CPU(s) list:   0-191
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Platinum 8468V
    CPU family:          6
    Model:               143
    Thread(s) per core:  2
    Core(s) per socket:  48
    Socket(s):           2
    Stepping:            8
    CPU max MHz:         3800.0000
    CPU min MHz:         800.0000
    BogoMIPS:            4800.00
```

Linux kernel:  6.5.0-18-generic

I believe the issue might be related to the environment module system not being properly set up or configured on my system. I would appreciate any guidance or suggestions on how to resolve this issue and successfully run the script.

**Comment by poyaesy** [comment]
We have updated the `README.md` in that folder  to avoid future confusions. The `module` commands are used to load prerequisites on MareNostrum 5 supercomputer located in Barcelona Supercomputing Center  [[1]](https://www.bsc.es/marenostrum/marenostrum-5), [[2]](https://www.bsc.es/supportkc/docs/MareNostrum5/overview).  

If you want to use this benchmark on your local server, you need to comment `module` commands and install the prerequisites specified `README.md` manually.

Please comment `module` commands and install the prerequisites manually. let me know if you face any other issue. 

[[1]](https://www.bsc.es/marenostrum/marenostrum-5) [https://www.bsc.es/marenostrum/marenostrum-5](https://www.bsc.es/marenostrum/marenostrum-5 ) 

[[2]](https://www.bsc.es/supportkc/docs/MareNostrum5/overview) [https://www.bsc.es/supportkc/docs/MareNostrum5/overview](https://www.bsc.es/supportkc/docs/MareNostrum5/overview )

**Comment by pudding-art** [comment]
Thank you.
