### ISSUE TITLE
Support for Graviton3

### ISSUE THREAD

**Issue by suyashmahar** [bsc-mem/Mess-benchmark#4]
Hi, I was trying to generate the latency-BW curves for graviton CPU, but noticed that the scripts are not updated.

For example, the runner.sh file here:
https://github.com/bsc-mem/Mess-benchmark/tree/main/CPU/Actual-hardware/ARM/Graviton3

If I were to fix the files, would I just need to modify runner.sh? Or are there other files I should also look at?

Thanks!

**Comment by poyaesy** [comment]
Hi, 

All files are correct except the README file. 
I have updated it. Please let me know if you face any problem.

**Comment by suyashmahar** [comment]
Thanks. I noticed that some other files (e.g., runner.sh) also needed updates. I think I had to do the same changes on my end and the benchmark seems to be working. TY!
